name: Scrape leetcode

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6,26,46 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Fetch latest data
        run: node scraper.js > profile.json

      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "fix: update latest data at ${timestamp}" || exit 0
          git push
